export const incentivesServiceData = [
    {
        id:"1",
        name:"Rahul",
        role:"Sales",
        sale:"",
        incentive:"",
        applicationForm:"",
        action:"action",
    },
    {
        id:"2",
        name:"Rohit",
        role:"Marketing",
        sale:"",
        incentive:"",
        applicationForm:"",
        action:"action",
    },
    {
        id:"3",
        name:"karan",
        role:"Sales",
        sale:"",
        incentive:"",
        applicationForm:"",
        action:"action",
    },
    ];