export const stockRegister2RowData = [
    {
        stkID: "1",
        stkItemDetails:"Nitco Marble",
        stkUom:"Pcs",
        stkShowroom1:"100",
        stkShowroom2:"200",
        stkWarehouse1:"300",
        stkWarehouse2:"400",
        stkTotal:"1000",
        stkAction:"action",
    },
    {
        stkID: "2",
        stkItemDetails:"Galaxy Marble",
        stkUom:"Pcs",
        stkShowroom1:"200",
        stkShowroom2:"50",
        stkWarehouse1:"0",
        stkWarehouse2:"0",
        stkTotal:"250",
        stkAction:"action",
    },
    {
        stkID: "3",
        stkItemDetails:"Black Marble",
        stkUom:"Pcs",
        stkShowroom1:"10",
        stkShowroom2:"10",
        stkWarehouse1:"500",
        stkWarehouse2:"1000",
        stkTotal:"1520",
        stkAction:"action",
    },
];