export const directPurchaseFormRowData = [
  {
    id: "1",
    item_details: {
      brand: "Marudhar",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    quantity_field: "100",
    rate_field: "rate_field",
    discPer_field: "0",
    discVal_field: "0",
    disc_field: "",
    cgst_field: "",
    gst_field: "",
    // sgst_field:"",
    // igst_field:"",
    net_value_field: "0",
    action: "add_purchase_item",
  },
  {
    id: "2",
    item_details: {
      brand: "Marudhar",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    quantity_field: "200",
    rate_field: "rate_field",
    discPer_field: "0",
    discVal_field: "0",
    disc_field: "",
    gst_field: "",
    cgst_field: "",
    // sgst_field:"",
    // igst_field:"",
    net_value_field: "0",
    value_field: "value_field",
    action: "add_purchase_item",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    quantity_field: "300",
    rate_field: "rate_field",
    discPer_field: "0",
    discVal_field: "0",
    disc_field: "",
    gst_field: "0",
    cgst_field: "",
    // sgst_field:"",
    // igst_field:"",
    net_value_field: "0",
    value_field: "value_field",
    action: "add_purchase_item",
  },
];
export const dummyRowData = [
  {
    id: "1",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    rate: "110",
    disc_field: "",
    cgst_field: "",
    sgst_field: "",
    igst_field: "",
    net_value_field: "0",
    value: "",
    quantity: "",
    action: "add_purchase_item",
  },
  {
    id: "2",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    quantity: "",
    rate: "120",
    disc_field: "",
    cgst_field: "",
    sgst_field: "",
    igst_field: "",
    net_value_field: "0",
    value: "",
    action: "add_purchase_item",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Marble",
      item: "[MM12952]",
      stock: "343",
      mrp: "15,000",
    },
    item_Img: "",
    quantity: "",
    rate: "180",
    disc_field: "",
    cgst_field: "",
    sgst_field: "",
    igst_field: "",
    net_value_field: "0",
    value: "",
    action: "add_purchase_item",
  },
];

export const addedItemServiceRowData = [
  {
    id: "1",
    item_details: {
      brand: "Marudhar",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "100 boxes",
    rate: "120",
    quantity_field: "100",
    disc_field: "5",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    net_value_field: "0",
    disc_per: "5",
    net_value: "15,000",
    value: "10.000",
    action: "action",
  },
  {
    id: "2",
    item_details: {
      brand: "Marudhar",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "200 Pieces",
    rate: "140",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    gst_field: "0",
    igst_field: "0",
    net_value_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
  {
    id: "3",
    item_details: {
      brand: "-",
      category: "Amazon white",
      item_own_code: "[MM12952]",
      itemName: "Glassy Marble",
    },
    item_Img: "",
    quantity: "300 boxes",
    rate: "220",
    disc_field: "0",
    cgst_field: "0",
    sgst_field: "0",
    igst_field: "0",
    gst_field: "0",
    disc_value: "50",
    disc_per: "5",
    net_value: "15,000",
    net_value_field: "0",
    value: "10,000",
    action: "action",
  },
];

import webApi from "../webApi/webApi";

//  comment
import { timestamp } from "../Utils/utils";

export const postDirectQuotation = async (
  info,
  allItems,
  enquiryDetails,
  chargesItem,
  onSuccess,
  onFailure
) => {
  // console.log(info.enquiry_status,"STATUS")
  try {
    const res = await webApi.post("/master/sales/insert", {
      module: "DIRECT_QUOTATION",
      customer_id: info.ddl_customer?.value,
      quotation_date: timestamp(info.txt_qut_date),
      quotation_note: info.txt_qut_note,
      quotation_status: info.quotation_status,
      enquiry_status: info.enquiry_status,

      status: 11,
     quotation_status: info.quotation_status,
        enquiry_details: {
        enquiry_date: timestamp(info.txt_qut_date),
        source_id: info.ddl_sales_source?.value,
        sales_executive_id: info.ddl_sales_executive?.value,
        showroom_warehouse_id: info.ddl_sales_showroom?.value,
        delivery_from_date: timestamp(info.date_sales_delivery_start),
        delivery_to_date: timestamp(info.date_sales_delivery_end),
        note: info.txt_qut_note,
        cust_name :info.ddl_customer?.label ,
        sales_exe_name:info.ddl_sales_executive?.label ,
        showroom_name :info.ddl_sales_showroom?.label ,
      },
      enquiry_item_details: enquiryDetails,
      quotation_item_details: allItems,
      quotation_other_charges : chargesItem,
      active_status: info.switch_active_status ? "Y" : "N",
    });
    if (res.status === 200) {
      const r = res.data;
      onSuccess(r);
    } else {
      onFailure("Something Wrong! Please Try again later " + res.data);
    }
  } catch (error) {
    onFailure("Something Wrong! Please Try again later " + error);
  }
};

export const updateQuotation = async (
  info,
  allItems,
  enquiryDetails,
  onSuccess,
  onFailure
) => {
  try {
    const res = await webApi.post("/master/quotation/update", {
      quotation_id: info.quotation_id,
      quotation_no: [info.txt_quotation_no],
      qut_date: timestamp(info.txt_qut_date),
      source_id: info.ddl_sales_source?.value,
      customer_id: info.ddl_customer?.value,
      sales_executive_id: info.ddl_sales_executive?.value,
      showroom_warehouse_id: info.ddl_sales_showroom?.value,
      delivery_from_date: timestamp(info.txt_sales_delivery_date),
      delivery_to_date: timestamp(info.txt_sales_delivery_end),
      note: info.txt_qut_note,
      enquiry_item_details: enquiryDetails,
      quotation_item_details: allItems,
      active_status: info.switch_active_status ? "Y" : "N",
    });
    if (res.status === 200) {
      const r = res.data;
      onSuccess(r);
    } else {
      onFailure("Something Wrong! Please Try again later " + res.data);
    }
  } catch (error) {
    onFailure("Something Wrong! Please Try again later " + error);
  }
};
